import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    id: 1,
    name: "Bella",
    gender: "Female",
    price: 350000,
    age: 6,
    image: "./images/products/PuppyImage-1.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],

    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 2,
    name: "Max",
    gender: "Male",
    price: 400000,
    age: 8,
    image: "/images/products/PuppyImage-2.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 3,
    name: "Luna",
    gender: "Female",
    price: 280000,
    age: 5,
    image: "/images/products/PuppyImage-3.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 4,
    name: "Charlie",
    gender: "Male",
    price: 320000,
    age: 7,
    image: "/images/products/PuppyImage-4.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 5,
    name: "Lucy",
    gender: "Female",
    price: 450000,
    age: 9,
    image: "/images/products/PuppyImage15.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 6,
    name: "Rocky",
    gender: "Male",
    price: 300000,
    age: 6,
    image: "/images/products/PuppyImage14.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 7,
    name: "Daisy",
    gender: "Female",
    price: 420000,
    age: 8,
    image: "/images/products/PuppyImage6.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 8,
    name: "Cooper",
    gender: "Male",
    price: 295800,
    age: 5,
    image: "/images/products/PuppyImage4.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
  {
    id: 9,
    name: "Molly",
    gender: "Female",
    price: 330000,
    age: 7,
    image: "/images/products/PuppyImage5.svg",
    thumbnails: [
      "/images/SinglePageThumbnails/Thumbnail-1.png",
      "/images/SinglePageThumbnails/Thumbnail-2.png",
      "/images/SinglePageThumbnails/Thumbnail-3.png",
      "/images/SinglePageThumbnails/Thumbnail-4.png",
    ],
    info: {
      sku: "#00178",
      gender: "Female",
      age: 6,
      size: "Small",
      color: "Apricot & Tan",
      vaccinated: true,
      dewormed: true,
      certified: true,
      certification: "MKA",
      microchip: true,
      location: "Vietnam",
      publishedDate: "12-Oct-2022",
      extra:
        ": Pure breed Shih Tzu.Good body structure.With MKA cert and Microchip.Father from champion lineage.",
    },
  },
];

const productsSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    getProducts: (state) => {
      console.log(state.products);
      return state.products;
    },
  },
});

export const { getProducts } = productsSlice.actions;
export const selectAllProducts = (state) => state.products;
export default productsSlice.reducer;
